export default[
    {
        id:1,
        name:'Programming',
        icon:'/code.png',
        prompt:''
    },
    {
        id:2,
        name:'Health',
        icon:'/health.png',
         prompt:''
    },
    {
        id:1,
        name:'creative',
        icon:'/creative.png',
         prompt:''
    },
]